services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juryhrms-admin
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3030
      - NUXT_PUBLIC_ENC_SECRET=wdhwvcdhvdw
      - NUXT_PUBLIC_API_BASE=http://103.102.234.246:50050
      - NUXT_PUBLIC_API_TRAFFIC_BASE=http://103.102.234.246:50064
      - NUXT_PUBLIC_API_USAGE_BASE=http://103.102.234.246:50065
    networks:
      - juryhrms-network
    restart: unless-stopped

networks:
  juryhrms-network:
    name: juryhrms-backend_default
