// constants/industries.ts
export const industries = [
    { label: 'Information Technology & Services', value: 'it-services', icon: 'lucide:cpu' },
    { label: 'Software (SaaS / Product)', value: 'software', icon: 'lucide:code' },
    { label: 'Computer Hardware', value: 'computer-hardware', icon: 'lucide:monitor' },
    { label: 'Telecommunications', value: 'telecom', icon: 'lucide:radio' },
    { label: 'E-commerce', value: 'ecommerce', icon: 'lucide:shopping-bag' },
    { label: 'Retail (Offline/Omni)', value: 'retail', icon: 'lucide:store' },
    { label: 'Wholesale & Distribution', value: 'wholesale', icon: 'lucide:package' },
    { label: 'Banking', value: 'banking', icon: 'lucide:banknote' },
    { label: 'Financial Services (Non-Banking)', value: 'financial-services', icon: 'lucide:wallet' },
    { label: 'Insurance', value: 'insurance', icon: 'lucide:shield-check' },
    { label: 'FinTech', value: 'fintech', icon: 'lucide:coins' },
    { label: 'Healthcare Providers', value: 'healthcare', icon: 'lucide:stethoscope' },
    { label: 'Pharmaceuticals', value: 'pharma', icon: 'lucide:pill' },
    { label: 'Biotechnology', value: 'biotech', icon: 'lucide:dna' },
    { label: 'Medical Devices', value: 'medical-devices', icon: 'lucide:activity' },
    { label: 'Education (K-12 / Higher Ed)', value: 'education', icon: 'lucide:graduation-cap' },
    { label: 'EdTech', value: 'edtech', icon: 'lucide:book-open' },
    { label: 'Manufacturing (General)', value: 'manufacturing', icon: 'lucide:factory' },
    { label: 'Automotive', value: 'automotive', icon: 'lucide:car' },
    { label: 'Aerospace & Defense', value: 'aerospace-defense', icon: 'lucide:rocket' },
    { label: 'Chemicals', value: 'chemicals', icon: 'lucide:flask-round' },
    { label: 'Textiles & Apparel', value: 'textiles-apparel', icon: 'lucide:shirt' },
    { label: 'FMCG / Packaged Goods', value: 'fmcg', icon: 'lucide:cup-soda' },
    { label: 'Food & Beverage', value: 'food-beverage', icon: 'lucide:utensils-crossed' },
    { label: 'Construction & Real Estate', value: 'construction-realestate', icon: 'lucide:building-2' },
    { label: 'Architecture & Design', value: 'architecture-design', icon: 'lucide:ruler' },
    { label: 'Civil Engineering', value: 'civil-engineering', icon: 'lucide:hammer' },
    { label: 'Logistics & Supply Chain', value: 'logistics', icon: 'lucide:truck' },
    { label: 'Warehousing', value: 'warehousing', icon: 'lucide:boxes' },
    { label: 'Shipping & Maritime', value: 'shipping', icon: 'lucide:ship' },
    { label: 'Aviation (Airlines/Services)', value: 'aviation', icon: 'lucide:plane' },
    { label: 'Railways', value: 'railways', icon: 'lucide:train' },
    { label: 'Energy (Oil & Gas)', value: 'energy-oil-gas', icon: 'lucide:flame' },
    { label: 'Power & Utilities', value: 'power-utilities', icon: 'lucide:plug' },
    { label: 'Renewables (Solar/Wind)', value: 'renewables', icon: 'lucide:sun' },
    { label: 'Mining & Metals', value: 'mining-metals', icon: 'lucide:pickaxe' },
    { label: 'Media & Entertainment', value: 'media-entertainment', icon: 'lucide:clapperboard' },
    { label: 'Advertising & Marketing', value: 'advertising-marketing', icon: 'lucide:megaphone' },
    { label: 'Gaming', value: 'gaming', icon: 'lucide:gamepad-2' },
    { label: 'Publishing', value: 'publishing', icon: 'lucide:newspaper' },
    { label: 'Professional Services (Consulting)', value: 'consulting', icon: 'lucide:briefcase' },
    { label: 'Legal Services', value: 'legal', icon: 'lucide:scales' },
    { label: 'Accounting', value: 'accounting', icon: 'lucide:calculator' },
    { label: 'Human Resources / Staffing', value: 'hr-staffing', icon: 'lucide:users' },
    { label: 'Hospitality (Hotels/Resorts)', value: 'hospitality', icon: 'lucide:bed-double' },
    { label: 'Travel & Tourism', value: 'travel-tourism', icon: 'lucide:luggage' },
    { label: 'Events & Exhibitions', value: 'events', icon: 'lucide:calendar-days' },
    { label: 'Sports & Recreation', value: 'sports', icon: 'lucide:trophy' },
    { label: 'Agriculture', value: 'agriculture', icon: 'lucide:wheat' },
    { label: 'AgriTech', value: 'agritech', icon: 'lucide:sprout' },
    { label: 'Forestry & Paper', value: 'forestry-paper', icon: 'lucide:trees' },
    { label: 'Fisheries & Aquaculture', value: 'fisheries', icon: 'lucide:fish' },
    { label: 'Public Sector & Government', value: 'public-sector', icon: 'lucide:landmark' },
    { label: 'Non-profit / NGOs', value: 'nonprofit', icon: 'lucide:heart-handshake' },
    { label: 'Defense & PSUs', value: 'defense-psu', icon: 'lucide:shield' },
    { label: 'Real Estate (Brokerage/Facilities)', value: 'real-estate-services', icon: 'lucide:home' },
    { label: 'Facilities Management', value: 'facilities', icon: 'lucide:key' },
    { label: 'Consumer Electronics', value: 'consumer-electronics', icon: 'lucide:smartphone' },
    { label: 'Semiconductors', value: 'semiconductors', icon: 'lucide:circuit-board' },
    { label: 'Cybersecurity', value: 'cybersecurity', icon: 'lucide:lock' },
    { label: 'Data & Analytics', value: 'data-analytics', icon: 'lucide:bar-chart-3' },
    { label: 'Artificial Intelligence', value: 'artificial-intelligence', icon: 'lucide:sparkles' },
]
