// app/stores/shared/theme.store.js
import { defineStore } from 'pinia'

export const useThemeStore = defineStore('Theme', {
    state: () => ({
        preloader: true,
        sidebar: true,

        // default background (brand-900)
        bgColor: '#0b283b',

        bgColors: [
            {
                label: 'Brand',
                key: 'brand',
                color: '#0b283b',
                shades: [
                    // { label: '50', color: '#f4f7fa' },
                    // { label: '100', color: '#e8f0f4' },
                    // { label: '200', color: '#d1e0ea' },
                    // { label: '300', color: '#afc9da' },
                    // { label: '400', color: '#8db2ca' },
                    // { label: '500', color: '#1b6594' },
                    // { label: '600', color: '#17567e' },
                    { label: '700', color: '#134768' },
                    { label: '800', color: '#0f3851' },
                    { label: '900', color: '#0b283b' },
                ],
            },
            {
                label: 'Rust',
                key: 'rust',
                color: '#3e180b',
                shades: [
                    // { label: '50', color: '#faf5f4' },
                    // { label: '100', color: '#f5ece8' },
                    // { label: '200', color: '#ebd8d1' },
                    // { label: '300', color: '#dcbbaf' },
                    // { label: '400', color: '#ce9e8d' },
                    // { label: '500', color: '#9c3c1b' },
                    // { label: '600', color: '#853317' },
                    { label: '700', color: '#6d2a13' },
                    { label: '800', color: '#56210f' },
                    { label: '900', color: '#3e180b' },
                ],
            },
            {
                label: 'Plum',
                key: 'plum',
                color: '#170f20',
                shades: [
                    // { label: '50', color: '#f5f4f6' },
                    // { label: '100', color: '#ebe9ee' },
                    // { label: '200', color: '#d7d4dc' },
                    // { label: '300', color: '#bab3c2' },
                    // { label: '400', color: '#9c92a8' },
                    // { label: '500', color: '#392651' },
                    // { label: '600', color: '#302045' },
                    { label: '700', color: '#281b39' },
                    { label: '800', color: '#1f152d' },
                    { label: '900', color: '#170f20' },
                ],
            },
            {
                label: 'Clay',
                key: 'clay',
                color: '#413128',
                shades: [
                    // { label: '50', color: '#faf8f7' },
                    // { label: '100', color: '#f6f2f0' },
                    // { label: '200', color: '#ece4e0' },
                    // { label: '300', color: '#ded0c9' },
                    // { label: '400', color: '#d0bcb2' },
                    // { label: '500', color: '#a27a65' },
                    // { label: '600', color: '#8a6856' },
                    { label: '700', color: '#715547' },
                    { label: '800', color: '#594338' },
                    { label: '900', color: '#413128' },
                ],
            },
            {
                label: 'Neutral',
                key: 'neutral',
                color: '#070a10',
                shades: [
                    // { label: '50', color: '#f3f3f4' },
                    // { label: '100', color: '#e7e8e9' },
                    // { label: '200', color: '#cfd1d4' },
                    // { label: '300', color: '#acaeb3' },
                    // { label: '400', color: '#888c93' },
                    // { label: '500', color: '#111827' },
                    // { label: '600', color: '#0e1421' },
                    { label: '700', color: '#0c111b' },
                    { label: '800', color: '#090d15' },
                    { label: '900', color: '#070a10' },
                ],
            },

            // Tailwind default palettes (hex values)
            {
                label: 'Red',
                key: 'red',
                color: '#7f1d1d',
                shades: [
                    // { label: '50', color: '#fef2f2' },
                    // { label: '100', color: '#fee2e2' },
                    // { label: '200', color: '#fecaca' },
                    // { label: '300', color: '#fca5a5' },
                    // { label: '400', color: '#f87171' },
                    // { label: '500', color: '#ef4444' },
                    // { label: '600', color: '#dc2626' },
                    { label: '700', color: '#b91c1c' },
                    { label: '800', color: '#991b1b' },
                    { label: '900', color: '#7f1d1d' },
                ],
            },
            {
                label: 'Blue',
                key: 'blue',
                color: '#1e3a8a',
                shades: [
                    // { label: '50', color: '#eff6ff' },
                    // { label: '100', color: '#dbeafe' },
                    // { label: '200', color: '#bfdbfe' },
                    // { label: '300', color: '#93c5fd' },
                    // { label: '400', color: '#60a5fa' },
                    // { label: '500', color: '#3b82f6' },
                    // { label: '600', color: '#2563eb' },
                    { label: '700', color: '#1d4ed8' },
                    { label: '800', color: '#1e40af' },
                    { label: '900', color: '#1e3a8a' },
                ],
            },
            {
                label: 'Green',
                key: 'green',
                color: '#064e3b',
                shades: [
                    // { label: '50', color: '#ecfdf5' },
                    // { label: '100', color: '#d1fae5' },
                    // { label: '200', color: '#a7f3d0' },
                    // { label: '300', color: '#6ee7b7' },
                    // { label: '400', color: '#34d399' },
                    // { label: '500', color: '#10b981' },
                    // { label: '600', color: '#059669' },
                    { label: '700', color: '#047857' },
                    { label: '800', color: '#065f46' },
                    { label: '900', color: '#064e3b' },
                ],
            },
            {
                label: 'Yellow',
                key: 'yellow',
                color: '#78350f',
                shades: [
                    // { label: '50', color: '#fffbeb' },
                    // { label: '100', color: '#fef3c7' },
                    // { label: '200', color: '#fde68a' },
                    // { label: '300', color: '#fcd34d' },
                    // { label: '400', color: '#fbbf24' },
                    // { label: '500', color: '#f59e0b' },
                    // { label: '600', color: '#d97706' },
                    { label: '700', color: '#b45309' },
                    { label: '800', color: '#92400e' },
                    { label: '900', color: '#78350f' },
                ],
            },
            {
                label: 'Orange',
                key: 'orange',
                color: '#7c2d12',
                shades: [
                    // { label: '50', color: '#fff7ed' },
                    // { label: '100', color: '#ffedd5' },
                    // { label: '200', color: '#fed7aa' },
                    // { label: '300', color: '#fdba74' },
                    // { label: '400', color: '#fb923c' },
                    // { label: '500', color: '#f97316' },
                    // { label: '600', color: '#ea580c' },
                    { label: '700', color: '#c2410c' },
                    { label: '800', color: '#9a3412' },
                    { label: '900', color: '#7c2d12' },
                ],
            },
            {
                label: 'Purple',
                key: 'purple',
                color: '#4c1d95',
                shades: [
                    // { label: '50', color: '#f5f3ff' },
                    // { label: '100', color: '#ede9fe' },
                    // { label: '200', color: '#ddd6fe' },
                    // { label: '300', color: '#c4b5fd' },
                    // { label: '400', color: '#a855f7' },
                    // { label: '500', color: '#8b5cf6' },
                    // { label: '600', color: '#7c3aed' },
                    { label: '700', color: '#6d28d9' },
                    { label: '800', color: '#5b21b6' },
                    { label: '900', color: '#4c1d95' },
                ],
            },
            {
                label: 'Pink',
                key: 'pink',
                color: '#831843',
                shades: [
                    // { label: '50', color: '#fdf2f8' },
                    // { label: '100', color: '#fce7f3' },
                    // { label: '200', color: '#fbcfe8' },
                    // { label: '300', color: '#f9a8d4' },
                    // { label: '400', color: '#f472b6' },
                    // { label: '500', color: '#ec4899' },
                    // { label: '600', color: '#db2777' },
                    { label: '700', color: '#be185d' },
                    { label: '800', color: '#9d174d' },
                    { label: '900', color: '#831843' },
                ],
            },
            {
                label: 'Lime',
                key: 'lime',
                color: '#365314',
                shades: [
                    // { label: '50', color: '#f7fee7' },
                    // { label: '100', color: '#ecfccb' },
                    // { label: '200', color: '#d9f99d' },
                    // { label: '300', color: '#bef264' },
                    // { label: '400', color: '#a3e635' },
                    // { label: '500', color: '#84cc16' },
                    // { label: '600', color: '#65a30d' },
                    { label: '700', color: '#4d7c0f' },
                    { label: '800', color: '#3f6212' },
                    { label: '900', color: '#365314' },
                ],
            },
            {
                label: 'Teal',
                key: 'teal',
                color: '#134e4a',
                shades: [
                    // { label: '50', color: '#f0fdfa' },
                    // { label: '100', color: '#ccfbf1' },
                    // { label: '200', color: '#99f6e4' },
                    // { label: '300', color: '#5eead4' },
                    // { label: '400', color: '#2dd4bf' },
                    // { label: '500', color: '#14b8a6' },
                    // { label: '600', color: '#0d9488' },
                    { label: '700', color: '#0f766e' },
                    { label: '800', color: '#115e59' },
                    { label: '900', color: '#134e4a' },
                ],
            },
            {
                label: 'Cyan',
                key: 'cyan',
                color: '#164e63',
                shades: [
                    // { label: '50', color: '#ecfeff' },
                    // { label: '100', color: '#cffafe' },
                    // { label: '200', color: '#a5f3fc' },
                    // { label: '300', color: '#67e8f9' },
                    // { label: '400', color: '#22d3ee' },
                    // { label: '500', color: '#06b6d4' },
                    // { label: '600', color: '#0891b2' },
                    { label: '700', color: '#0e7490' },
                    { label: '800', color: '#155e75' },
                    { label: '900', color: '#164e63' },
                ],
            },
        ],
    }),

    actions: {
        toggleSidebar() {
            this.sidebar = !this.sidebar
        },

        loadColor() {
            const saved = localStorage.getItem('bgColor')
            this.bgColor = saved || '#0b283b'
        },

        updateColor(color, shade) {
            const selected = shade?.color || color.color
            this.bgColor = selected
            localStorage.setItem('bgColor', selected)
        },
    },
})
